name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  phar-release:
    name: PHAR
    runs-on: ubuntu-latest

    if: github.repository == 'mogic-le/changelog-helper'

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare Phar for upload
      run: |
        mv builds/changelog-helper builds/changelog-helper.phar
    
    - uses: CSchoel/release-notes-from-changelog@v1

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          builds/changelog-helper.phar
        body_path: RELEASE.md
